SELECT
    ORDER_ID,
    TO_DATE(ORDER_DATE, 'MM/DD/YY') AS ORDER_DATE,
    SEGMENT,
    STATE,
    CATEGORY,
    SUB_CATEGORY,
    PRODUCT_NAME,
    SALES,
    QUANTITY,
    DISCOUNT,
    PROFIT,
    SALES - PROFIT AS COST,
    SALES * (1 - DISCOUNT) AS NET_SALES
FROM {{ ref('bronze_orders') }}
WHERE SALES IS NOT NULL 
  AND QUANTITY > 0
