version: 2

sources:
  - name: stg
    database: SUPERSTORE_DB
    schema: STAGING
    tables:
      - name: orders_raw
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: ORDER_DATE
      - name: customers_raw
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: UPDATED_AT
