SELECT
    STATE,
    CATEGORY,
    SUM(SALES) AS TOTAL_SALES,
    SUM(PROFIT) AS TOTAL_PROFIT,
    SUM(NET_SALES) AS TOTAL_NET_SALES,
    SUM(QUANTITY) AS TOTAL_UNITS
FROM {{ ref('silver_orders') }}
GROUP BY 1, 2
ORDER BY TOTAL_SALES DESC
